# This workflow will build then upload the plugin to infrastructure.tech.

name: Publish Plugin

on:
  release:
    types: [created]

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonpickle ebbs
    - name: Build and publish
      run: |
        ebbs -v -l publish generated --repo-username ${{ secrets.INFRASTRUCTURE_USERNAME }} --repo-password ${{ secrets.INFRASTRUCTURE_PASSWORD }} --version ${{ github.event.release.tag_name }} --visibility 'private'
